#include <stdio.h>
#include "httpd.h"
#include "http_config.h"
#include "http_request.h"

request_rec req = {
    .pool = (apr_pool_t *)0x7fffe8002ba8,
    .connection = (conn_rec *)0x7fff78000f90,
    .server = (server_rec *)0x5555556347b0,
    .next = NULL,
    .prev = NULL,
    .main = NULL,
    .the_request = (char *)0x7fffe8004188,
    .assbackwards = 0,
    .proxyreq = 0,
    .header_only = 0,
    .proto_num = 1001,
    .protocol = (char *)0x7fffe8004178,
    .hostname = (char *)0x7fffe80045c0,
    .request_time = 1719893898303309,
    .status_line = NULL,
    .status = 200,
    .method_number = 0,
    .method = (char *)0x7fffe8004168,
    .allowed = 0,
    .allowed_xmethods = NULL,
    .allowed_methods = (apr_array_header_t *)0x7fffe8002f00,
    .sent_bodyct = 0,
    .bytes_sent = 0,
    .mtime = 0,
    .range = NULL,
    .clength = 0,
    .chunked = 0,
    .read_body = REQUEST_NO_BODY,
    .read_chunked = 0,
    .expecting_100 = 0,
    .kept_body = NULL,
    .body_table = NULL,
    .remaining = 0,
    .read_length = 0,
    .headers_in = (apr_table_t *)0x7fffe8002f40,
    .headers_out = (apr_table_t *)0x7fffe80037e0,
    .err_headers_out = (apr_table_t *)0x7fffe8003a28,
    .subprocess_env = (apr_table_t *)0x7fffe8003460,
    .notes = (apr_table_t *)0x7fffe8003d68,
    .content_type = NULL,
    .handler = NULL,
    .content_encoding = NULL,
    .content_languages = NULL,
    .vlist_validator = NULL,
    .user = NULL,
    .ap_auth_type = NULL,
    .unparsed_uri = (char *)0x7fffe80041a8,
    .uri = (char *)0x7fffe80041b8,
    .filename = NULL,
    .canonical_filename = NULL,
    .path_info = NULL,
    .args = NULL,
    .used_path_info = AP_REQ_DEFAULT_PATH_INFO,
    .eos_sent = 0,
    .per_dir_config = (ap_conf_vector_t *)0x55555563d300,
    .request_config = (apr_table_t *)0x7fffe8003f08,
    .log = NULL,
    .log_id = NULL,
    .htaccess = NULL,
    .output_filters = (ap_filter_t *)0x7fffe8004068,
    .input_filters = (ap_filter_t *)0x7fffe8004598,
    .proto_output_filters = (ap_filter_t *)0x7fffe8004068,
    .proto_input_filters = (ap_filter_t *)0x7fffe8004598,
    .no_cache = 0,
    .no_local_copy = 0,
    .invoke_mtx = (apr_thread_mutex_t *)0x7fffe80045d0,
    .parsed_uri = {
        .scheme = NULL,
        .hostinfo = NULL,
        .user = NULL,
        .password = NULL,
        .hostname = NULL,
        .port_str = NULL,
        .path = (char *)0x7fffe80041b8,
        .query = NULL,
        .fragment = NULL,
        .hostent = NULL,
        .port = 0,
        .is_initialized = 1,
        .dns_looked_up = 0,
        .dns_resolved = 0},
    .finfo = {.pool = NULL, .valid = 0, .protection = 0, .filetype = APR_NOFILE, .user = 0, .group = 0, .inode = 0, .device = 0, .nlink = 0, .size = 0, .csize = 0, .atime = 0, .mtime = 0, .ctime = 0, .fname = NULL, .name = NULL, .filehand = NULL},
    .useragent_addr = (apr_sockaddr_t *)0x7fff78000df0,
    .useragent_ip = (char *)0x7fff780012f8,
    .trailers_in = (apr_table_t *)0x7fffe80032c0,
    .trailers_out = (apr_table_t *)0x7fffe8003bc8,
    .useragent_host = NULL,
    .double_reverse = 0,
    .bnotes = NULL};

int main()
{
    printf("hello world\n");
    ap_process_request_internal(&req);
}
